import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {extractDocument} from '../server/document-text.mjs';
function pdf(text){const stream=`BT /F1 12 Tf 50 700 Td (${text}) Tj ET`;const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`];let content='%PDF-1.4\n',offsets=[0];for(let i=0;i<objects.length;i++){offsets.push(content.length);content+=`${i+1} 0 obj\n${objects[i]}\nendobj\n`;}const xref=content.length;content+=`xref\n0 6\n0000000000 65535 f \n`+offsets.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n \n').join('')+`trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return Buffer.from(content).toString('base64');}
test('extracts PDF résumé text with word and token estimates',async()=>{const result=await extractDocument({name:'resume.pdf',data:pdf('SQL reporting experience')});assert.equal(result.text,'SQL reporting experience');assert.equal(result.words,3);assert.ok(result.estimatedTokens>0);});
test('extracts actual DOCX paragraphs',async()=>{const data=(await readFile(new URL('./fixtures/resume.docx',import.meta.url))).toString('base64');const result=await extractDocument({name:'resume.docx',data});assert.match(result.text,/Example Candidate\n\nSQL reporting/);});
test('rejects unsupported, corrupt, empty and oversized documents',async()=>{await assert.rejects(extractDocument({name:'resume.exe',data:'YQ=='}),/Upload/);await assert.rejects(extractDocument({name:'resume.pdf',data:'YQ=='}),/valid PDF/);await assert.rejects(extractDocument({name:'resume.txt',data:Buffer.from(' ').toString('base64')}),/No readable text/);await assert.rejects(extractDocument({name:'resume.txt',data:Buffer.alloc(30001,65).toString('base64')}),/30,000/);await assert.rejects(extractDocument({name:'resume.doc',data:'YQ=='}),/Could not read/);});
test('extracts legacy Word DOC content',async()=>{const data=(await readFile(new URL('./fixtures/resume.doc',import.meta.url))).toString('base64');const result=await extractDocument({name:'resume.doc',data});assert.match(result.text,/Example Candidate/);assert.match(result.text,/SQL reporting/);});
