import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {Skills} from '../server/skills.mjs';
import {AgentProfiles} from '../server/agents.mjs';
import {ProviderConfig} from '../server/provider-config.mjs';
test('skills persist, legacy instructions remain available and agents test with selected skill and model',async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'cf-skills-'));try{const calls=[],storage=new ProviderConfig({directory:dir,env:{}});const ai={config:storage,catalog:async()=>({answer:['test-model']}),generate:async args=>{calls.push(args);return {answer:'Supported response',model:'test-model'}}};const skills=new Skills(storage,ai),agents=new AgentProfiles(ai);agents.skillLibrary=skills;assert.equal(skills.list().length,5);const old=await agents.save({name:'Existing',skills:'Existing instructions',provider:'test',model:'test-model',context:{}});assert.ok(skills.list().some(s=>s.content==='Existing instructions'));assert.equal(skills.list().length,6);const saved=skills.save({name:'My skill',content:'Explain clearly'});const agent=await agents.save({name:'Linked',skills:'ignored',skillId:saved.id,provider:'test',model:'test-model',responseStyle:'interview',context:{content:'JD data',additionalContent:'Resume data'}});const pinned=agents.get(agent.id);skills.save({...saved,content:'Updated instruction'});assert.equal(pinned.skills,'Explain clearly');assert.equal(agents.get(agent.id).skills,'Updated instruction');await agents.test({id:agent.id,question:'Explain the approach'});assert.equal(calls.length,1);assert.equal(calls[0].selection.model,'test-model');assert.match(calls[0].system,/Updated instruction/);assert.match(calls[0].system,/Use general technical knowledge/);assert.match(calls[0].system,/never turn JD requirements/);assert.equal(JSON.parse(calls[0].question).referenceContent.additionalContent,'Resume data');assert.equal(new Skills(new ProviderConfig({directory:dir,env:{}}),ai).get(saved.id).content,'Updated instruction');assert.throws(()=>skills.save({name:'Bad',content:''}),/instructions/);await assert.rejects(agents.save({...agent,skillId:'missing'}),/Skill not found/);await assert.rejects(skills.generate({content:''}),/source content/);}finally{fs.rmSync(dir,{recursive:true,force:true})}});
