import InterviewProfile from './InterviewProfile.jsx';
import Skills from './Skills.jsx';
import React,{useEffect,useState} from 'react';
import ReactMarkdown from 'react-markdown';
import {CopyablePre} from './CopyButton.jsx';
import MeetingContext from './MeetingContext.jsx';
const blank=()=>({name:'',responseStyle:'meeting',provider:'',model:'',skills:'',skillId:'',context:{content:'',additionalContent:'',files:[],prompt:''}});
export default function Agents({request}){
 const [tab,setTab]=useState('agents');
 return <div className="agents-view"><h2>Agents & skills</h2><div className="cf-modal-tabs"><button className={tab==='agents'?'active':''} onClick={()=>setTab('agents')}>Agents</button><button className={tab==='skills'?'active':''} onClick={()=>setTab('skills')}>Skills</button></div>{tab==='agents'?<AgentEditor request={request}/>:<Skills request={request}/>}</div>;
}
function AgentEditor({request}){
 const [agents,setAgents]=useState([]),[skills,setSkills]=useState([]),[providers,setProviders]=useState([]),[models,setModels]=useState([]),[draft,setDraft]=useState(blank),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[uploading,setUploading]=useState(false),[testQuestion,setTestQuestion]=useState(''),[testResult,setTestResult]=useState(null);
 const selectedSkill=skills.find(s=>s.id===draft.skillId),skillText=selectedSkill?.content||draft.skills||'';
 async function catalog(provider){try{setModels((await request('providers/'+provider)).answer)}catch(e){setModels([]);setError(e.message)}}
 async function load(){const [a,s,k]=await Promise.all([request('agents'),request('settings'),request('skills')]);setAgents(a.agents);setSkills(k.skills);setProviders(s.providers.filter(p=>p.roles.includes('answer')&&(p.local||p.hasKey)));}
 useEffect(()=>{load().catch(e=>setError(e.message))},[]);
 function choose(agent){setDraft(agent);setNotice('');setError('');setTestResult(null);if(agent.provider)catalog(agent.provider);else setModels([])}
 async function work(fn){setBusy(true);setError('');setNotice('');try{await fn()}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <><p>Select an agent to edit or test it. Create and upload reusable skills in the Skills tab.</p><div className="agent-library-list">{agents.map(a=><button key={a.id} className={draft.id===a.id?'cf-primary':'cf-secondary'} disabled={busy||uploading} onClick={()=>choose(a)}>{a.name}</button>)}<button className="cf-secondary" disabled={busy||uploading} onClick={()=>choose(blank())}>Create new agent</button></div><fieldset disabled={busy||uploading}><label>Agent name<input value={draft.name} maxLength={100} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><div className="meeting-context-grid"><label>Answer provider<select value={draft.provider} onChange={e=>{setDraft({...draft,provider:e.target.value,model:''});catalog(e.target.value)}}><option value="">Choose a connected provider</option>{providers.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Answer model<select value={draft.model} onChange={e=>setDraft({...draft,model:e.target.value})}><option value="">Choose a model</option>{models.map(m=><option key={m}>{m}</option>)}</select></label></div><label>Response style<select value={draft.responseStyle||'meeting'} onChange={e=>setDraft({...draft,responseStyle:e.target.value})}><option value="meeting">Meeting · concise reply</option><option value="interview">Interview · explain and end with example</option></select></label>{draft.responseStyle==='interview'&&<InterviewProfile value={draft.interview} onChange={interview=>setDraft({...draft,interview})} disabled={busy||uploading}/>}
 <label>Choose a saved skill<select aria-label="Choose a saved skill" value={draft.skillId||''} onChange={e=>{const skill=skills.find(s=>s.id===e.target.value);setDraft({...draft,skillId:e.target.value,skills:skill?.content||''})}}><option value="">{draft.skills&&!draft.skillId?'Existing agent instructions':'No skill selected'}</option>{skills.map(s=><option key={s.id} value={s.id}>{s.name}{s.builtin?' · Built-in':''}</option>)}</select></label>{skillText&&<details><summary>View selected skill</summary><pre className="skill-preview">{skillText}</pre></details>}<small>Manage skill files and instructions in Skills. Changes to a saved skill apply to new meetings; active meetings keep their starting version.</small>
 <MeetingContext key={draft.id||'new'} onBusyChange={setUploading} interview={draft.responseStyle==='interview'} value={draft.context} onChange={context=>setDraft({...draft,context})} disabled={busy} request={(path,options)=>path==='meeting-prompt'?request(path,{...options,body:JSON.stringify({...JSON.parse(options.body),selection:{provider:draft.provider,model:draft.model},skills:skillText})}):request(path,options)}/>
 {draft.responseStyle==='interview'&&<button className="cf-secondary" disabled={!draft.model} onClick={()=>work(async()=>{const guide=await request('agent-guidance',{method:'POST',body:JSON.stringify({...draft,skills:skillText})});setDraft(prev=>({...prev,interview:{emailDetails:prev.interview?.emailDetails||'',expectations:prev.interview?.expectations||'',detectedStage:guide.stage,stageReason:guide.stageReason},context:{...prev.context,prompt:guide.prompt}}));setNotice('Stage: '+guide.stage+'. '+guide.stageReason+' Answer guide updated; the selected skill is unchanged. Save the agent to use it.');})}>Generate interview answer guide</button>}
 <button className="cf-primary" disabled={!draft.name.trim()||!draft.model} onClick={()=>work(async()=>{const d=await request('agents',{method:'POST',body:JSON.stringify({...draft,skills:skillText})});setDraft(d.agent);await load();setNotice('Agent and references saved locally. Ready to test or select in a meeting.');})}>Save agent & content</button>
 <section className="agent-test"><h3>Test saved agent</h3><p>Uses this agent’s saved model, selected skill, JD, résumé and answer guide. Save edits first. This sends one request to its answer provider.</p><label>Test question<textarea aria-label="Agent test question" maxLength={2000} value={testQuestion} onChange={e=>setTestQuestion(e.target.value)} placeholder="Ask a question to check how this agent responds…"/></label><button className="cf-secondary" disabled={!draft.id||testQuestion.trim().length<4} onClick={()=>work(async()=>{setTestResult(null);setTestResult(await request('agents/test',{method:'POST',body:JSON.stringify({id:draft.id,question:testQuestion})}));})}>Test agent</button>{testResult&&<div className="cf-markdown"><small>{testResult.provider} · {testResult.model}</small><ReactMarkdown components={{pre:CopyablePre}}>{testResult.answer}</ReactMarkdown></div>}</section></fieldset>{busy&&<p role="status">Working…</p>}{notice&&<p role="status">{notice}</p>}{error&&<p role="alert" className="cf-inline-error">{error}</p>}</>;
}
