import CopyButton,{CopyablePre} from './CopyButton.jsx';
import React,{useEffect,useState} from 'react';
import ReactMarkdown from 'react-markdown';
export default function MeetingHistory({request}){
 const [items,setItems]=useState([]),[selected,setSelected]=useState(null),[error,setError]=useState('');
 async function load(){try{setItems((await request('meetings')).meetings)}catch(e){setError(e.message)}}
 useEffect(()=>{load()},[]);
 async function download(){const url=URL.createObjectURL(new Blob([JSON.stringify(selected,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='meeting-'+selected.id+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 return <div className="meeting-history"><h2>Meeting history</h2><p>Review saved transcripts, questions, answers and recordings.</p><button className="cf-secondary" onClick={load}>Refresh history</button><select aria-label="Saved meeting" value={selected?.id||''} onChange={async e=>{try{setSelected(e.target.value?await request('meetings/'+e.target.value):null)}catch(e){setError(e.message)}}}><option value="">Choose a meeting</option>{items.map(m=><option key={m.id} value={m.id}>{new Date(m.startedAt).toLocaleString()} · {m.name} · {m.turns} turns</option>)}</select>{!items.length&&<p>No saved meetings yet.</p>}{error&&<p role="alert">{error}</p>}{selected&&<><h3>{selected.source.name}</h3>{selected.recording?<><audio key={selected.id} controls preload="metadata" src={'/api/meetings/'+selected.id+'/recording'}/><a className="cf-secondary" href={'/api/meetings/'+selected.id+'/recording?download=1'} download>Download recording (.wav)</a></>:<p>This older meeting has no saved audio recording.</p>}<button className="cf-secondary" onClick={download}>Download transcript & answers</button><details><summary>Reference content & prompt</summary><pre>{JSON.stringify(selected.context||{},null,2)}</pre></details><h3>Transcript</h3>{selected.turns.map(t=><article className="meeting-turn" key={t.id}><b>{t.speaker}</b><time>{new Date(t.at).toLocaleTimeString()}</time><p>{t.text}</p></article>)}<h3>Questions & answers</h3>{selected.questions.map(q=><article className="meeting-question" key={q.id}><h4>{q.text}</h4>{q.answer&&<CopyButton text={q.answer}/>}<ReactMarkdown components={{pre:CopyablePre}}>{q.answer||q.error||q.status}</ReactMarkdown></article>)}</>}</div>
}
