import React,{useState} from 'react';
export default function MeetingContext({value,onChange,disabled,request,interview=false,onBusyChange=()=>{}}){
 const stats=text=>`${(text?.match(/\S+/g)||[]).length.toLocaleString()} words · ~${Math.ceil((text||'').length/4).toLocaleString()} tokens`;
 const total=[value.content,value.additionalContent,...value.files.map(f=>f.text),value.prompt].filter(Boolean).join('\n');
 const [error,setError]=useState(''),[generating,setGenerating]=useState(false),[uploading,setUploading]=useState('');
 const modes=Object.fromEntries(Object.entries(value.inputs||{}).map(([key,input])=>[key,input.mode]));
 const names=Object.fromEntries(Object.entries(value.inputs||{}).map(([key,input])=>[key,input.name]));
 const locked=disabled||!!uploading;
 async function upload(file,key){if(!file)return;setError('');setUploading(key);onBusyChange(true);try{
  if(file.size>5*1024*1024)throw Error('Upload a document under 5 MB.');
  const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(Error('Could not read this file.'));reader.readAsDataURL(file);});
  const result=await request('document-text',{method:'POST',body:JSON.stringify({name:file.name,data})});
  onChange({...value,[key]:result.text,inputs:{...value.inputs,[key]:{mode:'file',name:result.name}}});
 }catch(e){setError(e.message)}finally{setUploading('');onBusyChange(false)}}
 return <details className="meeting-context" open><summary>{interview?'Job description, résumé & answer prompt':'Meeting content & answer prompt'}</summary><p className="meeting-info">Total: {stats(total)} · Token counts are estimates; actual usage depends on the model.</p><div className="meeting-context-grid">{['content','additionalContent'].map((key,i)=>{
  const label=interview?(i?'Résumé':'Job description'):(i?'Additional content':'Content');
  return <div key={key}><label>{label} input<select aria-label={label+' input type'} value={modes[key]||'content'} disabled={locked} onChange={e=>onChange({...value,inputs:{...value.inputs,[key]:{mode:e.target.value,name:names[key]||''}}})}><option value="content">Paste content</option><option value="file">Upload file</option></select></label>{modes[key]==='file'&&<label>Upload {label.toLowerCase()} · PDF or Word<input aria-label={'Upload '+label} type="file" accept=".pdf,.docx,.doc,.txt,.md" disabled={locked} onChange={e=>{upload(e.target.files?.[0],key);e.target.value=''}}/><small>{uploading===key?'Extracting text locally…':names[key]||'PDF, DOCX, DOC or text · up to 5 MB'}</small></label>}{(modes[key]!=='file'||value[key])&&<label>{modes[key]==='file'?'Extracted text · review and edit':label}<textarea aria-label={label} disabled={locked} value={value[key]} maxLength={30000} placeholder={'Paste '+label.toLowerCase()+' here…'} onChange={e=>onChange({...value,[key]:e.target.value})}/></label>}<small>{stats(value[key])}</small></div>;
 })}</div>{value.files.length>0&&<details><summary>Previously attached references</summary>{value.files.map((f,i)=><p key={i}>{f.name} · {stats(f.text)} <button disabled={locked} onClick={()=>onChange({...value,files:value.files.filter((_,n)=>n!==i)})}>Remove</button></p>)}</details>}<label>Answer prompt<textarea aria-label="Meeting answer prompt" disabled={locked||generating} maxLength={8000} value={value.prompt} placeholder="Describe how you want answers written…" onChange={e=>onChange({...value,prompt:e.target.value})}/></label><button className="cf-secondary" disabled={locked||generating} onClick={async()=>{setGenerating(true);setError('');try{const d=await request('meeting-prompt',{method:'POST',body:JSON.stringify({context:value})});onChange({...value,prompt:d.prompt});}catch(e){setError(e.message)}finally{setGenerating(false)}}}>{generating?'Generating prompt…':'Generate prompt from content'}</button><p className="meeting-info">Uploaded documents are extracted locally. Review the text, then save your agent or start the meeting to use it. This text is sent to your selected answer provider when generating prompts or answers.</p>{error&&<p role="alert" className="cf-inline-error">{error}</p>}</details>;
}
