import React,{useEffect,useRef,useState} from 'react';
import ReactMarkdown from 'react-markdown';
import CopyButton,{CopyablePre} from './CopyButton.jsx';
export default function ResponseWindow(){
 const [state,setState]=useState({questions:[]}),[error,setError]=useState(''),[size,setSize]=useState(20),[follow,setFollow]=useState(true);const pane=useRef(null);
 const workspace=new URLSearchParams(location.search).get('workspace')||'default',desktop=window.contextflowDesktop;
 useEffect(()=>{if(!desktop)return;const events=new EventSource('/api/live/events?workspace='+encodeURIComponent(workspace));events.onmessage=e=>{setState(JSON.parse(e.data));setError('')};events.onerror=()=>setError('Reconnecting to ContextFlow…');return()=>events.close()},[workspace]);
 useEffect(()=>{if(follow&&pane.current)pane.current.scrollTop=pane.current.scrollHeight},[state,size,follow]);
 return <main className="response-window"><header><h2>Responses{state.agent?.name?' · '+state.agent.name:''}</h2><label>Answer text size <input aria-label="Answer text size" type="range" min="14" max="32" value={size} onChange={e=>setSize(Number(e.target.value))}/>{size}px</label></header>{!desktop?<section><p>Open the native desktop window to request capture protection.</p><button onClick={async()=>{try{const r=await fetch('/api/response-window?workspace='+encodeURIComponent(workspace),{method:'POST'});const d=await r.json();if(!r.ok)throw Error(d.error);setError('Desktop window requested.')}catch(e){setError(e.message)}}}>Open desktop responses</button></section>:<small>{desktop.platform==='win32'?'Capture protection requested. Verify the remote view before relying on it.':'Capture protection requested; macOS screen sharing may still show this window. Share only your presentation window for privacy.'}</small>}{error&&<p role="status">{error}</p>}<div ref={pane} className="meeting-response-content" style={{'--response-text-size':size+'px',overflow:'auto',flex:1}} onScroll={e=>{const p=e.currentTarget;setFollow(p.scrollHeight-p.scrollTop-p.clientHeight<80)}}>{!state.questions?.length&&<p>Start a meeting in this workspace. Answers will appear here live.</p>}{state.questions?.map(q=><article className="meeting-question" key={q.id}><h4>{q.text}</h4><small>{q.model} · {q.status}</small><CopyButton text={q.answer||''}/><div className="meeting-answer-text"><ReactMarkdown components={{pre:CopyablePre,img:()=>null}}>{q.answer||q.error||'Waiting for answer…'}</ReactMarkdown></div></article>)}</div><button onClick={()=>setFollow(true)}>Follow latest answer</button></main>
}
